---
- name: Install Docker
  hosts: all
  become: true

  tasks:
  - name: Install yum utils
    yum:
      name: 
        - yum-utils
        - device-mapper-persistent-data
        - lvm2
      state: latest
  - name: creating a docker repository
    yum_repository:
      description: repo for docker
      name: docker-ce
      baseurl: https://download.docker.com/linux/centos/8/x86_64/stable/
      gpgkey: https://download.docker.com/linux/centos/gpg
      gpgcheck: yes
  - name: install docker-ce
    yum:
      name:
        - docker-ce
      state: present
  - name: get docker version
    shell: "docker -v"
    register: version
  - debug: var=version.stdout
